spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/cl?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    #整合mybatis
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    publisher-confirm-type: correlated
    publisher-returns: true
  thymeleaf:
    cache: false
  mail:
    host: smtp.qq.com
    port: 587
    username: 1670844920@qq.com
    password: kptflealcvbfcggd
    nickname: Clara
    properties:
      mali:
        smtp:
          auth: true
          starttls:
          enable: true
  redis:
    # 地址
    host: 192.168.50.1
    # 端口号
    port: 6379
    # 密码
    #password: 123456
    # 超时时间，单位毫秒
    timeout: 3000
    # 数据库编号
    database: 0
    # 配置lettuce
mybatis:
  type-aliases-package: com.yu.springboot_jdbc_mybatis.pojo
  mapper-locations: classpath:mybatis\*.xml
server:
  port: 9000
#  ssl:
#    enabled: true
#    key-store: classpath:tomcat.keystore
#    key-store-type: JKS
#    key-store-password: 666666
#    key-alias: tomcat
#  http:
#    multipart:
#    max-file-size: 100MB
#    max-request-size: 200MB
logging:
  level:
    root: info
    com.yu.springboot_jdbc_mybatis: debug #日志级别
  file:
    name: run.log
    path: ./
